### ISSUE TITLE
first-login: "location you choose" or "location you chose"

### ISSUE THREAD

**Issue by jbicha** [CanonicalLtd/desktop-design#102]
"first login"  _Welcome to Ubuntu_ wizard

According to the [Google doc](https://docs.google.com/a/canonical.com/document/d/1IDQwpqTsB7Cmw413ApXioHeO2E9nv8bHugjxCOg9A-Q/edit), the wording for the _Help improve Ubuntu_ page should say "the approximate location you chose", but in https://github.com/CanonicalLtd/desktop-design/issues/66#issuecomment-377261986 it has the wording "the approximate location you choose". Note the difference in the final word. We implemented the second wording in Ubuntu 18.04 but I think _chose_ is a better verb tense here.

**Comment by matthewpaulthomas** [comment]
Well spotted @jbicha. By “chose” I was referring to the time zone you have already chosen in the installer or in oem-setup. “Choose” would not make sense here, because there is no UI for choosing again before the report is sent.

**Comment by matthewpaulthomas** [comment]
(To explain the closing: this repo is design-only, and here there’s nothing to change in the design. If code changes are still required, please track those on Launchpad if necessary.)

**Comment by jbicha** [comment]
@gunnarhj Do you have any suggestions for how we could make this string change in English without breaking translations?

Do we need to keep both the old string and the new string because users doing a clean 18.04 install won't receive the SRU of gnome-initial-setup until after the (first) user completes the welcome wizard?

**Comment by gunnarhj** [comment]
@jbicha: If you now upload with the new string, and notify the translators about it, the old string will still be in the .mo files until the first langpack update, and thus fresh installs correctly translated (of the incorrect string...). That's the way I see for a relatively smooth change.

**Comment by gunnarhj** [comment]
(Artificially having both strings in the template would be to overdo it, wouldn't it?)

**Comment by jbicha** [comment]
@gunnarhj Ok, but I think language packs are installed and/or updated at the end of the install (assuming internet access) but other SRUs (or even security updates) are downloaded (optionally) but not installed. That means that your suggestion would break as soon as we have a language pack update, right?
