### ISSUE TITLE
first-login: should "Software" be "Ubuntu Software"?

### ISSUE THREAD

**Issue by seb128** [CanonicalLtd/desktop-design#109]
The issue has been reported on https://bugs.launchpad.net/ubuntu/+source/gnome-initial-setup/+bug/1767281

"The "Software" mentioned in the "Ready to go" tab will link to the "Ubuntu Software".

Maybe this string should be changed to "Ubuntu Software" instead."

**Comment by matthewpaulthomas** [comment]
This was an error on my part. It should be “Ubuntu Software” (or whatever the app happens to be named at the time).
