### ISSUE TITLE
first-login: tweak location formatting

### ISSUE THREAD

**Issue by jbicha** [CanonicalLtd/desktop-design#110]
In the _Welcome to Ubuntu_ wizard, my location is shown as `America/New_York`. This has a few issues.

1. I'd expect the `_` to be removed so `America/New York'

2. Should we include the region or not?
a. `New York` is a bit bad because I am in Florida and New York is over 1000 miles away from me (but we share the same time zone currently.) `Shanghai` is a similar problem for China.
b. On the other hand, `America/Edmonton` isn't good either because `America` generally refers to the United States, while Americas or North America represent larger regions. I imagine including `America` would look like a typo or error to many people in Canada. I guess I can probably come up with more examples where the region is annoying than where it is helpful.

3. If the person doing the wizard is the same as the one who did the install, then `New York` might make sense but I imagine many people will also think it is a mistake since the page doesn't indicate that this is merely the timezone. Although it would be a major change, maybe it's better to just be more straightforward with wording like `and the timezone you chose during installation.`

_Originally reported at [LP: #1765233](https://launchpad.net/bugs/1765233)_

![ubuntu-welcome-20180503-help-improve](https://user-images.githubusercontent.com/876259/39606551-fb3d8442-4f03-11e8-9dc2-afadd4f8d84a.png)

**Comment by matthewpaulthomas** [comment]
If there is no file listing a human-sensible name for each time zone location, then let’s drop it and just say “the time zone you chose” instead.
