### ISSUE TITLE
[gnome-software] Custom header artwork mockups

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/desktop-design#123]
Following up from #115:

We need mockups showing custom header artwork for example apps, plus mockups showing fallback generated artwork for other example apps.

Once complete, they should be attached to [the GitLab issue](https://gitlab.gnome.org/GNOME/gnome-software/issues/415).

**Comment by therealjuan** [comment]
Can we add estimation points?

**Comment by spencerbygraves** [comment]
@matthewpaulthomas Can I have some more info on this please? I'm not sure what this involves. Thanks.

**Comment by matthewpaulthomas** [comment]
@spencerbygraves Sure.
1. Take same-sized screenshots, of the Gnome Software app view, for five or six apps.
2. Alter the screenshots to make room for a header image in the app view, partly overlapped by the content, as shown in the wireframes in [the GitLab issue](https://gitlab.gnome.org/GNOME/gnome-software/issues/415).
3. Devise a way to generate an attractive, but unobtrusive, pattern based on an app’s icon. (For a first iteration, maybe the same pattern each time, with the app icon determining only the pattern’s colors. For possible inspiration, look at the wall behind your desk.) Demonstrate this for two of the apps.
4. For the other 3~4 apps, fill the same space with custom artwork or photography that suits the app. For inspiration, see the Web sites for [Wunderlist](https://www.wunderlist.com/) and [ActiveInbox](https://www.activeinboxhq.com/), and the Microsoft Store listings for [Adobe Photoshop Elements](https://www.microsoft.com/en-us/p/adobe-photoshop-elements-2018/9pnh63vfkmv5?cid=msft_web_appsforwindows_spotlight&activetab=pivot%3Aoverviewtab), [HD Movie Maker Pro](https://www.microsoft.com/en-us/p/hd-movie-maker-pro/9n9kbwp6hvqq?cid=msft_web_appsforwindows_chart&activetab=pivot%3Aoverviewtab), [Drawboard PDF](https://www.microsoft.com/en-us/p/drawboard-pdf/9wzdncrfhwqt?cid=msft_web_appsforwindows_chart&activetab=pivot%3Aoverviewtab), and [Weather Radar Pro](https://www.microsoft.com/en-us/p/weather-radar-pro/9wzdncrdkwnq?cid=msft_web_appsforwindows_chart&activetab=pivot%3Aoverviewtab).

**Comment by spencerbygraves** [comment]
@matthewpaulthomas, here are the designs we discussed earlier.

For the pattern set, I have used a white SVG with opacity over the coloured background. I have also used a gradient made from the dominant colour, reduced in brightness by 20% on the left side. It would be good if this could be achieved when choosing the dominant colour, I guess we would need to ask.

### 1. ###

![image](https://user-images.githubusercontent.com/9105999/42635389-dfdd2980-85dd-11e8-8acb-c09ab06dad96.png)

### 2. ###

![image](https://user-images.githubusercontent.com/9105999/42635456-000113ca-85de-11e8-8cd0-314f356e9bf8.png)

### 3. ###

![image](https://user-images.githubusercontent.com/9105999/42635488-16d20f00-85de-11e8-8aa7-5490922563ac.png)

The second set using photography.

### 1. ###

![image](https://user-images.githubusercontent.com/9105999/42635700-a5c71520-85de-11e8-9883-a56e412d8787.png)

### 2. ###

![image](https://user-images.githubusercontent.com/9105999/42635726-b9e5d032-85de-11e8-93c2-7e1fc88b3759.png)

### 3. ###

![image](https://user-images.githubusercontent.com/9105999/42635759-d33a02f6-85de-11e8-9009-c235ed3ca9b4.png)

At the minimum width, perhaps the pattern could narrow. I'm not sure that would work for images as the content isn't responsive.

![image](https://user-images.githubusercontent.com/9105999/42636174-fbcb0430-85df-11e8-990c-cfddc05c19ee.png)

Thanks.

**Comment by spencerbygraves** [comment]
Thanks @matthewpaulthomas, I've updated those images above.

**Comment by matthewpaulthomas** [comment]
Thanks @spencerbygraves! I’ve [posted the updated images upstream](https://gitlab.gnome.org/GNOME/gnome-software/issues/415#note_268540).

**Comment by lyubomir-popov** [comment]
@matthewpaulthomas I looked at the file, the background is composed of 2 parts:
1) linear gradient between 2 shades (not sure who will be picking the colours for those), for example linear-gradient(to right, #29B360 0%, #1D8045 100%)
2) 3 transparent shapes - https://assets.ubuntu.com/v1/c73546e0-folds.svg the size is 1200x199, but it can be resized or clipped as needed.

**Comment by matthewpaulthomas** [comment]
Thanks @lyubomir-popov. [Posted to GitLab](https://gitlab.gnome.org/GNOME/gnome-software/issues/415#note_334285).
