### ISSUE TITLE
Review examples of data visualisation and dashboards

### ISSUE THREAD

**Issue by Greggless** [CanonicalLtd/desktop-design#125]
DO NOT USE PINTEREST OR DRIBBBLE BECAUSE ITS A LOAD OF CRAP

**Comment by Greggless** [comment]
## Calculating the chance of alien life with [this interactive graph](https://informationisbeautiful.net/visualizations/the-drake-equation/)

**Comment by Greggless** [comment]
## DATA VIZ 📈 [Diversity in tech](https://informationisbeautiful.net/visualizations/diversity-in-tech/)
![image](https://user-images.githubusercontent.com/23459065/42821035-8602eabc-89cf-11e8-8996-65b88d1bb181.png)
- View by year
- Compares series against multiple categories

**Comment by Greggless** [comment]
## DATA VIZ 📉 [Google's Diversity report](https://diversity.google/annual-report/)

**Comment by Greggless** [comment]
# Dashboard :pager: [aprilzero.com](http://aprilzero.com/)
- A very cool dashboard giving insight into a Silicon Valley-goer's techie life. 
- Allowing navigation into deep levels of data and cross navigation into relevant data, too.
![image](https://user-images.githubusercontent.com/23459065/42893412-2530a41c-8aac-11e8-8b64-af5dfa3628f3.png)

**Comment by 8none1** [comment]
In case you're interested here's the Steam survey:

https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam?platform=linux

**Comment by Greggless** [comment]
We should think whether users are going to be more interested in looking at trends or comparisons for each of the data points. For some of the data it makes sense to look at variables over time. The yearly toggle takes a a slice per year when _comparing_ values. Plotting the same on an area chart (or other trend-based data chart) might not work for the intended purposes.

**Comment by Greggless** [comment]
# Google analytics
### Active users
Overview panel representing currently active users:
  - Single value - Total active users
  - Sparkline - recent active users
  - Listing - Top active pages
  - Ability to dive into details

![image](https://user-images.githubusercontent.com/23459065/43128141-171aa87e-8f29-11e8-9f67-8006b0213c8e.png)

### When do your users visit? A customisable Heatmap
- Comparing multiple variables on one chart; Time of day, day, and frequency of occurence
- Time variable select toggles view over last X days

![image](https://user-images.githubusercontent.com/23459065/43128578-3c50a66a-8f2a-11e8-9be9-a0cf107c21ca.png)

### Where are your users? A combined chart
- A tiny world map isn't very useful, but it's accompanied by a bar chart listing top values as part of a summary
![image](https://user-images.githubusercontent.com/23459065/43128972-35071776-8f2b-11e8-968f-9a20e326e848.png)
