### ISSUE TITLE
Brief: Dashboard statistics 

### ISSUE THREAD

**Issue by kasiag** [CanonicalLtd/desktop-design#128]
From Will Cooke; [Ubuntu report: Internal metrics](https://docs.google.com/document/d/1BsREyYASPMIsAtiwzq5DpmeZHt_ZnJ1uZuxOIbfXZ30/edit?usp=sharing). Create a brief from the kick-off meeting and the Report. 

Using this to create a [working document](https://docs.google.com/document/d/1qABX3xEIBTl4d4brcHyEC9v7mtfaOy3jYnWbEKXZZK0/edit?usp=sharing) to inform design process

**Comment by Greggless** [comment]
[Brief updated](https://docs.google.com/document/d/1bCRMmEvnh41Pkht810euXvMTrohL7JT9QwNKwMi6-fA/edit?usp=sharing) pending review from @8none1 

Psst, Hey Will! would you mind looking over the brief and check I'm aligned with your thinking for the Dashboard?

**Comment by 8none1** [comment]
+1 doc looks good.  Thanks!
