### ISSUE TITLE
Brief: Move software updates and others into settings

### ISSUE THREAD

**Issue by kasiag** [CanonicalLtd/desktop-design#129]

**Comment by matthewpaulthomas** [comment]
Mailed @8none1 requesting description of the scope here.

**Comment by 8none1** [comment]
This Trello card has more details:

https://trello.com/c/2zzukqWH

and this one:

https://trello.com/c/d6hsAglg

Is the one being worked on at the moment.

Please work directly with Robert, he's doing the implementation and has prioritised the list so we can try and get at least some of them done this cycle.

**Comment by matthewpaulthomas** [comment]
Thanks @8none1.

[Brief drafted](https://docs.google.com/document/d/1AD6dJ9qRkEmBwzBjH-RepqV_hIA2TlrjD6l7J60HezQ/edit). @kasiag @carlaberkers Please excuse any mistakes, since it’s the first time I’ve used this particular brief template.

**Comment by matthewpaulthomas** [comment]
From review:
- Need to talk with Robert Ancell about scheduling
- Probably best to just let him port what exists, and review and give feedback afterwards.
- Add some basic user testing to the plan (roughly 1 day prep, 1 day testing, 1 day write-up).

**Comment by matthewpaulthomas** [comment]
There’s no time zone overlap between Robert and me, so I’ve e-mailed him.

I’ve recorded the user testing task as #132.

**Comment by matthewpaulthomas** [comment]
Mailed Robert again.

**Comment by matthewpaulthomas** [comment]
[Draft brief](https://docs.google.com/document/d/1AD6dJ9qRkEmBwzBjH-RepqV_hIA2TlrjD6l7J60HezQ/edit) revised.

**Comment by carlaberkers** [comment]
Is this reviewed by @8none1 and Robert? Are they happy with the items in scope for 18.10 or would they like to narrow it down?

**Comment by 8none1** [comment]
+1 from me

**Comment by matthewpaulthomas** [comment]
@carlaberkers The “Scope” section is based entirely on mail from Robert.

**Comment by matthewpaulthomas** [comment]
Brief approved by @carlaberkers.

⚠ This work is not included in the August 6th plan for the rest of this cycle. I’ve reported #139 to track it.
