### ISSUE TITLE
Can't distinguish between active and inactive tabs in gedit

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#13]

**Comment by kwm14** [comment]
@8none1 @didrocks can you provide a screenshot so we have a visual reference. Thanks

**Comment by kwm14** [comment]
Design spec for Gedit tab states added to Code [here](https://github.com/CanonicalLtd/desktop-design/tree/master/Active%20and%20inactive%20tabs%20in%20Gedit).

**Comment by 8none1** [comment]
We wont fix this now.  All future work will go towards communitheme and so this issue can be closed.
