### ISSUE TITLE
Brief: Refinement of first-run wizard

### ISSUE THREAD

**Issue by kasiag** [CanonicalLtd/desktop-design#130]

**Comment by matthewpaulthomas** [comment]
[Draft design brief](https://docs.google.com/document/d/123vX6vveI8u0fLw412TRUMJ-og6pEbQwFvfROGQCkwU/edit).

**Comment by matthewpaulthomas** [comment]
To do:
- [ ] Talk with @8none1 about which of the listed items are in scope.

**Comment by matthewpaulthomas** [comment]
Call scheduled for Tuesday.

**Comment by matthewpaulthomas** [comment]
Will made one addition to the tasks, but is otherwise happy with the brief.
