### ISSUE TITLE
Transparency of top bar needs tweaking

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#14]
If you have a light coloured wallpaper it can be difficult to read the clock and icons when the top bar is transparent.

**Comment by spencerbygraves** [comment]
The design of the top bar now has a solid colour of #111111. The design can be seen [here](https://github.com/CanonicalLtd/desktop-design/issues/36#issuecomment-358338949)

**Comment by matthewpaulthomas** [comment]
(Reopening because the bug hasn’t been fixed yet.)

**Comment by 8none1** [comment]
We wont fix this now.  All future work will go towards communitheme and so this issue can be closed.
