### ISSUE TITLE
Livepatch status menu icon

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/desktop-design#146]
We want people to be able to see Livepatch status in the “top bar” (the black bar along the top of the Ubuntu screen).

This requires a monochrome status icon — similar to those for wi-fi or Bluetooth — with two states, on and off.

[Livepatch](https://www.ubuntu.com/livepatch) doesn’t currently have any icon or logo of its own.

Metaphor fodder: Livepatch automatically applies some security updates in the background, making your system safer. So, possibilities include a sticking plaster (like Photoshop’s Healing tools), a shield (like antivirus software often has), or a fabric patch (like Photoshop’s Patch tool).

**Comment by 8none1** [comment]
My 2 cents: a shield is a good metaphor.

**Comment by spencerbygraves** [comment]
@matthewpaulthomas @8none1 we currently have a shield on the [ESM page](https://www.ubuntu.com/esm), or we have the shield below.

![image](https://user-images.githubusercontent.com/9105999/51903713-c81dea80-23b4-11e9-8a0c-810a2db1aad3.png)

However, I don't think these were designed to be used at small sizes and don't have different states for on and off.

@waynecrosby will soon be designing a new set of icons so perhaps this could be included as part of that work.

**Comment by 8none1** [comment]
@spencerbygraves hi!  Are you able to give an ETA on the icon?

**Comment by spencerbygraves** [comment]
@8none1 Hi, we'll be working on it this week. Thanks.

**Comment by azzar1** [comment]
@spencerbygraves Any news on this? The branch to add the indicator is almost ready and we need the icons in order to propose it :)

**Comment by spencerbygraves** [comment]
@azzar1, @marcush will be sending the icons to @8none1 this afternoon. Thanks.

**Comment by matthewpaulthomas** [comment]
Is anything more needed here, or can this be closed

**Comment by waynecrosby** [comment]
It can be closed. Thanks W
