### ISSUE TITLE
Design GUI for installing theme snap

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/desktop-design#147]
Popular GTK themes, including the default themes in popular Linux OSes, are included in [the gtk-common-themes snap](https://snapcraft.io/gtk-common-themes) so that they can connect to installed snaps.

If you install a theme that isn’t included in that package, there may be a snap to provide that theme to installed snaps. If so, you should be prompted to install it, and notified of installation progress, error, or success.

When the installation succeeds, you should also be prompted to relaunch snaps that have windows open, so that they can pick up the theme.

**Comment by matthewpaulthomas** [comment]
Initial prompt:
![theme-snap-prompt](https://user-images.githubusercontent.com/19801137/53172243-22415280-35e5-11e9-940a-7596767d1db3.png)

If you choose “Download”: (halfway through, “Downloading” would change to “Installing”)
![theme-snap-downloading](https://user-images.githubusercontent.com/19801137/53172244-22415280-35e5-11e9-9757-958341e6b039.png)

If there’s an error:
![theme-snap-error](https://user-images.githubusercontent.com/19801137/53172241-22415280-35e5-11e9-8949-73652c38d509.png)

If installation succeeds, and any snaps have open GTK windows:
![theme-snap-success](https://user-images.githubusercontent.com/19801137/53172240-21a8bc00-35e5-11e9-8baa-bfb4b04fe8b8.png)

@kenvandine @jhenstridge Feedback welcome.

**Comment by clagom** [comment]
@matthewpaulthomas I'm not able to change assign people either

**Comment by matthewpaulthomas** [comment]
Good suggestion from @kwm14: Add a “Relaunch All” button to handle the case where there are many open snap apps.

**Comment by clagom** [comment]
+1 on "relaunch all" button

**Comment by matthewpaulthomas** [comment]
Revised design for when any apps need relaunching:

![theme-snap-success](https://user-images.githubusercontent.com/19801137/54989015-8de55980-4faf-11e9-9200-4e28e913c45b.png)

**Comment by matthewpaulthomas** [comment]
[Specification updated](https://wiki.ubuntu.com/Appearance?action=diff&rev2=52&rev1=51).
