### ISSUE TITLE
“Channels” software settings complete design

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/desktop-design#149]
[The Software & Updates Settings design](https://wiki.ubuntu.com/SoftwareAndUpdatesSettings) begins with a “Channels” tab (combining the previous “Ubuntu Software”, “Other Software”, and “Authentication” tabs).

This tab is not fully specified, in particular:
- [x] Clarifying that software also comes from the Snap Store
- [x] What happens when you check/uncheck a channel
- [x] The “Install software from a CD/DVD/volume” label should be updated
- [x] What does the “Install software from…” menu contain
- [x] ~~“Choose File…” should always be enabled (choosing a file should auto-check the radio button)~~
- [x] What happens when you add a channel

**Comment by matthewpaulthomas** [comment]
@clagom Do you have time to review this? Thanks.

**Comment by clagom** [comment]
Looks good to me @matthewpaulthomas 
The only thing I wonder is here:
![](https://wiki.ubuntu.com/SoftwareAndUpdatesSettings?action=AttachFile&do=get&target=settings-channels.png)
The paragraph below says "The “Official channels” header should have a radio menu for choosing the download server... [and so on]"
Is this part missing from the sketches?

**Comment by matthewpaulthomas** [comment]
@clagom The radio menu is shown to the right of the “Official channels” header text, with the current value “UK”.
