### ISSUE TITLE
Tweak default icon size in launcher

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#15]
The default size is too large.

**Comment by kwm14** [comment]
@8none1 @didrocks @3v1n0 do you know what the current default size is? Thanks

**Comment by kwm14** [comment]
## Icon size in Launcher

The default icon size is set to `48px`, but as a user you can change the size of icons in the Dock via Settings.

Speaking with the brand team:
- The default icon size has been worked out with Mark for many years
- It's also a brand issue and sits comfortable in the space
- For users it's about your initial interaction with the desktop
- Going forward the default icon is to remain at `48px`
