### ISSUE TITLE
Errored fields are too red

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#16]
If you enter invalid text in to an input field the entire field turns red.

**Comment by 8none1** [comment]
![error_field](https://user-images.githubusercontent.com/6552931/33721230-50fc1e26-db5e-11e7-9383-d0e7431c2ab3.png)

**Comment by spencerbygraves** [comment]
A field with an error should be white with a 2px border. Designs will be added to code in the Error folder.

![error](https://user-images.githubusercontent.com/9105999/35056471-dbc172c0-fba9-11e7-8941-b59e4b2b438a.png)

**Comment by matthewpaulthomas** [comment]
(Reopening because the bug hasn’t been fixed yet.)

**Comment by matthewpaulthomas** [comment]
This won’t be fixed, since Ubuntu no longer ships Ambiance and Radiance.
