### ISSUE TITLE
Installer LVM changes - Final Designs

### ISSUE THREAD

**Issue by cristinadresch** [CanonicalLtd/desktop-design#168]
Figma Clickable Prototype: https://www.figma.com/proto/0oKbszYR8kIfdogBIrYj5W/Ubuntu-22.04-LTS-Desktop-Installer-LVM?page-id=1%3A3680&node-id=1%3A3681&viewport=241%2C48%2C0.08&scaling=min-zoom&starting-point-node-id=1%3A3681&show-proto-sidebar=1

Zeplin: https://zpl.io/bemKk7z

Specs: https://docs.google.com/document/d/1JxPQyBaXSfqgnKKolAfuG5_FgzUFiWJyMJd-BV8N6YI/edit

**Comment by elioqoshi** [comment]
@spencerbygraves If you could have a quick look at the designs and there is nothing horribly wrong?
