### ISSUE TITLE
Wireframes/Mockups

### ISSUE THREAD

**Issue by elioqoshi** [CanonicalLtd/desktop-design#170]
Provide wireframes or mockups for attaching the UA token in the Desktop installer.

**Comment by elioqoshi** [comment]
The first pass for the online flow should be ready for UX Review now:
https://www.figma.com/file/rvsmL34dPmR4jcKEcTAbg5/UA-in-Desktop-Installer?node-id=0%3A1

Once this flow is good to go I will continue with the offline flow based on it. Having a session with @lechsandecki to go over this later today as well.

**Comment by wgx** [comment]
UX +1 ! with some optional notes for @elioqoshi to consider.
