### ISSUE TITLE
Spec Document - First draft

### ISSUE THREAD

**Issue by elioqoshi** [CanonicalLtd/desktop-design#174]
Create a Google Doc with the feature specs and screenshots to align PdM and Engineering.

**Comment by elioqoshi** [comment]
First draft is ready! https://docs.google.com/document/d/1KxcPi9P7ftKgwJ2sWJcAADD5aAtAfTSZevcSZetQ7iQ/edit#

This is good to go for a review but we will have a meeting with Mark together with @waynecrosby as well on 9th of March so it can officially be signed off only afterwards.

Assigning @wgx for a UX review, I have done a few changes on the token Verification UX because of technical limitations.

**Comment by wgx** [comment]
LGTM +1
