### ISSUE TITLE
Checkboxes highlight just the label but should highlight the whole field

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#18]

**Comment by 8none1** [comment]
![checkbox_highlight_18](https://user-images.githubusercontent.com/6552931/33720960-7802a82e-db5d-11e7-893b-42e4ae07e965.png)

**Comment by clobrano** [comment]
Here is a possible fix for this
https://code.launchpad.net/~c-lobrano/ubuntu-themes/fix-checkbutton-and-radiobutton-highlight/+merge/335443

![checkbuttons-after](https://user-images.githubusercontent.com/2883614/34204903-b9028a7e-e580-11e7-85d5-4c0e0dafaebb.png)

the same MR fixes also radiobuttons in the same way

**Comment by 3v1n0** [comment]
Fix is coming in ubuntu-themes - 16.10+18.04.20180122.1-0ubuntu1 (just landed in `proposed`)
