### ISSUE TITLE
Link buttons become buttons when clicked but should remain as just text

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#19]

**Comment by clobrano** [comment]
MP for this issue https://code.launchpad.net/~c-lobrano/ubuntu-themes/ut-fix-link-button-mouseover/+merge/335136

![link-button](https://user-images.githubusercontent.com/2883614/33940201-5e1ef4c0-e00e-11e7-8306-1899bd570d3f.gif)

**Comment by 3v1n0** [comment]
I'm not sure what's the designed solution for this, should they be still the same color when unfocused, and not using any underline normally?

**Comment by kwm14** [comment]
@clobrano your MP looks good from Design :+1:

Only one change to make is the link colour which we've recently updated:

### Visual
![llnks](https://user-images.githubusercontent.com/17748020/35048862-37dd6e88-fb96-11e7-9446-f919eaf60c2a.png)

### Spec
- Text color: `#007aa6`
- No underline
- Hover state: Text underline

**Comment by clobrano** [comment]
What about the backdrop state? It should keep the new color, or is it ok if it goes gray?

**Comment by kwm14** [comment]
@clobrano what do you mean by backdrop state? could you add a screenshot so I have a visual reference. Thanks :slightly_smiling_face:

**Comment by clobrano** [comment]
@kwm14 I meant when the windows goes out of focus. Please refer to the gif above when the shell goes on focus

**Comment by kwm14** [comment]
@clobrano oh I see what you mean now. It should remain the same new colour I provided. Thanks

**Comment by clobrano** [comment]
MP updated
![link-button-blue](https://user-images.githubusercontent.com/2883614/35062846-b0903b1a-fbc5-11e7-9171-3e331ea7183e.gif)

**Comment by kwm14** [comment]
@clobrano looks good. Thanks 👍

**Comment by kwm14** [comment]
Design approved and Code needs approving on Launchpad. Closing issue.

**Comment by matthewpaulthomas** [comment]
(Reopening because [the proposal](https://code.launchpad.net/~c-lobrano/ubuntu-themes/ut-fix-link-button-mouseover/+merge/335136) hasn’t been merged yet.)

**Comment by 3v1n0** [comment]
Fix is coming in ubuntu-themes - 16.10+18.04.20180122.1-0ubuntu1 (just landed in `proposed`)

**Comment by jbicha** [comment]
There's a complaint about the link color changing from orange to blue.
See https://launchpad.net/bugs/1749103

**Comment by gunnarhj** [comment]
I'm one of the complainers. :wink:

AFAIU, this issue is about modifying the link button behavior. Isn't there a way to do that without changing the link color globally? Or, if that can't be done easily, is there a way to control the link color specifically for e.g. yelp?

GNOME :heart: blue - Ubuntu :heart: orange

**Comment by clobrano** [comment]
I should double check to see if keeping the orange color in yelp is possible, but in general it's easy to bring it back to orange everywhere. First MP version was like that, than @kwm14 asked for the change

**Comment by fitojb** [comment]
Oh, puhlease. Finally we have a nice color for links without contrast issues and which doesn’t give me headaches!!

**Comment by gunnarhj** [comment]
Personally I can possibly get used to the blue. What really made me react was the lack of information about this global change of the link color. Also, when @3v1n0 closed the bug report and referred to this issue, I expected to see some kind of justification for the change of link color. I see no such thing.

Please note that the Ubuntu Desktop Guide, which you see when running the `yelp` command, is also published on [help.ubuntu.com](https://help.ubuntu.com/stable/ubuntu-help/). Orange links all through, which up to now matched the link color when viewing the pages with `yelp`.

Is there possibly some information about this global link color change which I ought to have seen but missed? If not, there is room for improvement as regards the way the design team communicates.

Are we expected to change the link color at [help.ubuntu.com](https://help.ubuntu.com/stable/ubuntu-help/) to get compliant again?

**Comment by fitojb** [comment]
@gunnarhj https://docs.vanillaframework.io/en/settings/color-settings

**Comment by gunnarhj** [comment]
Thanks @fitojb. That was news to me, and provides the justification I asked for.

I take it that the answer to my last question is "yes" then, and that there are reasons to have a look at the style sheets used at [help.ubuntu.com](https://help.ubuntu.com/).

**Comment by 8none1** [comment]
We wont fix this now.  All future work will go towards communitheme and so this issue can be closed.
