### ISSUE TITLE
Radio buttons do not highlight the whole field when pressed

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#22]

**Comment by clobrano** [comment]
Here is a possible fix for this
https://code.launchpad.net/~c-lobrano/ubuntu-themes/fix-checkbutton-and-radiobutton-highlight/+merge/335443

![radiobuttons-after](https://user-images.githubusercontent.com/2883614/34204971-f21b5520-e580-11e7-874e-39b197470863.png)


the same MR fixes also checkbuttons in the same way

**Comment by 3v1n0** [comment]
Fix is coming in ubuntu-themes - 16.10+18.04.20180122.1-0ubuntu1 (just landed in `proposed`)
