### ISSUE TITLE
Focus ring for segmented buttons doesnt highlight the whole button

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#24]

**Comment by clobrano** [comment]
Trying to apply here a fix similar to the one for [issue 25](https://github.com/CanonicalLtd/desktop-design/issues/25), but using border-color in place of border-image I am not sure what do to when in hover state.

Currently it is like the following

![segmented-button-hover-before](https://user-images.githubusercontent.com/2883614/34948233-e690be84-fa0c-11e7-831e-b5da417f0737.gif)


Current change is in [this branch](https://code.launchpad.net/~c-lobrano/ubuntu-themes/fix-focus-ring-segmented-buttons) and looks like this (and it lacks of a proper hover effect)

![segmented-button-hover-after-no-hover](https://user-images.githubusercontent.com/2883614/34948195-c6e7d324-fa0c-11e7-9ca9-5d0de692045d.gif)

 Using a lighter orange would be a good solution?

**Comment by clobrano** [comment]
Just to give an idea (third one looks best to me, but it doesn't work like the other widgets)

1. lighter border color
![ambiance-segm-buttons-hover-lighter](https://user-images.githubusercontent.com/2883614/35046387-229a9efa-fb97-11e7-9048-9aa63b28cbdc.gif)

2. darker border color
![ambiance-segm-buttons-hover-darker](https://user-images.githubusercontent.com/2883614/35046399-2b50f5f8-fb97-11e7-9173-bc377ade0a08.gif)

3. thicker border
![ambiance-segm-buttons-hover-thicker](https://user-images.githubusercontent.com/2883614/35046404-2faed336-fb97-11e7-9189-68971631b723.gif)

**Comment by matthewpaulthomas** [comment]
This won’t be fixed now, since Ubuntu no longer ships Ambiance and Radiance.
