### ISSUE TITLE
Focus ring for combo boxes doesn't highlight the whole button

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#25]

**Comment by 8none1** [comment]
![combo_focus_ring_25](https://user-images.githubusercontent.com/6552931/33720850-2713e996-db5d-11e7-8502-0b27386f9683.png)

**Comment by clobrano** [comment]
I have a possible solution for that, but it requires to replace the border-image with a "normal" colored border, since (as far as I know) it isn't possible to make the border-image corners square

**Comment by 8none1** [comment]
I'm fine with that. I wonder if it will be faster without an image border as well?  Might be.

**Comment by clobrano** [comment]
Here is the MP https://code.launchpad.net/~c-lobrano/ubuntu-themes/focus-ring-for-combo-boxes/+merge/334986

**Comment by 8none1** [comment]
Awesome, thanks @clobrano! Would you be able to do a "before" and "after" screenshot so that design can quickly ack?

**Comment by clobrano** [comment]
Sure, can I copy it here?

**Comment by 8none1** [comment]
Yes please, upload the screenshots here.

**Comment by clobrano** [comment]
Before and after images for first, middle and last child entries

![focus-ring-entry-b4-after](https://user-images.githubusercontent.com/2883614/33781336-792b483a-dc54-11e7-877e-703c2dfa0d31.png)

**Comment by 8none1** [comment]
@carlaberkers could you have someone +1 these changes from the visual side of things?

**Comment by matthewpaulthomas** [comment]
Thanks to @lyubomir-popov for approving the visual design.

**Comment by 3v1n0** [comment]
Fix is coming in ubuntu-themes - 16.10+18.04.20180122.1-0ubuntu1 (just landed in `proposed`)
