### ISSUE TITLE
Grey background appears in step fields

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#26]

**Comment by 8none1** [comment]
![stepfield](https://user-images.githubusercontent.com/6552931/33439446-5908697c-d5e5-11e7-87fc-edb799dae529.png)

**Comment by clobrano** [comment]
Here a possible fix for this issue https://code.launchpad.net/~c-lobrano/ubuntu-themes/ut-bug-step-field-grey-bg/+merge/335558

This should also fix some other issues I saw with borders and vertical spinbuttons.

Horizontal spinbuttons before and after the fix
![spinbutton-horizontal-before](https://user-images.githubusercontent.com/2883614/34304954-54176220-e73c-11e7-90e5-fb844c0cbeca.gif)
![spinbutton-horizontal-after](https://user-images.githubusercontent.com/2883614/34304957-58e2c9f2-e73c-11e7-9c9b-51adfc72e89b.gif)

Vertical spinbuttons before and after the fix
![spinbutton-vertical-before](https://user-images.githubusercontent.com/2883614/34305005-8cfde550-e73c-11e7-9c97-58058dee7b69.gif)
![spinbutton-vertical-after](https://user-images.githubusercontent.com/2883614/34305009-8ebb2c90-e73c-11e7-9830-c285ae3c9ed1.gif)

**Comment by 3v1n0** [comment]
Fix is coming in ubuntu-themes - 16.10+18.04.20180122.1-0ubuntu1 (just landed in `proposed`)
