### ISSUE TITLE
Nautilus path bar buttons are inconsistent

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#28]
There are a lot of different greys in the breadcrumbs at the top of the Nautilus window which need some rationalisation.

**Comment by 8none1** [comment]
![nautilus_greys_28](https://user-images.githubusercontent.com/6552931/33713519-6f5ad418-db43-11e7-92a8-f71a9773d36f.png)

**Comment by kwm14** [comment]
@Luxamman @madsrh would you be able to provide me with a SVG of the Nautilus path bar? Thanks

**Comment by madsrh** [comment]
@kwm14 no, sorry. If you find an SVG could you upload it here: https://github.com/CanonicalLtd/desktop-design/

**Comment by kwm14** [comment]
## Nautilus path bar

- Updated color palette to use correct greys
- Buttons are now distinguished from active vs disabled states
- Pathbar has a consistent style

![nautilus-path-bar-buttons](https://user-images.githubusercontent.com/17748020/35109776-38189e5c-fc6f-11e7-9e2b-b86f46656fe1.png)

**Comment by kwm14** [comment]
Design spec can be found in Code under Nautilus path bar [here](https://github.com/CanonicalLtd/desktop-design/tree/master/Nautilus%20path%20bar). Closing issue.

**Comment by matthewpaulthomas** [comment]
(Reopening because the specified changes haven’t been made yet.)

**Comment by 3v1n0** [comment]
@kwm14 I don't think this solution can be applied to Ambiance, do you have any idea for this (based on @8none1 screenshot)?

**Comment by madsrh** [comment]
The dark gray currently used for the disabled state, looks IMO more like a pressed (down state) button.

What about something like this: (using the screenshot from [this issue](https://github.com/CanonicalLtd/desktop-design/issues/27) as reference)

![nautilus-ambiance](https://user-images.githubusercontent.com/3986894/37865873-e111d71c-2f82-11e8-9f4e-37f44c6328e7.jpg)

**Comment by 3v1n0** [comment]
Yeah, it's a really good idea... Could you help with some css code for that?

**Comment by madsrh** [comment]
@3v1n0 I wish 😞 
@clobrano do you have time to look into this? and if you do, could you add the pressed state for [the stackswitcher](https://github.com/CanonicalLtd/desktop-design/issues/64) as well?

**Comment by clobrano** [comment]
Hi! Sure, let me see what can I do

**Comment by 3v1n0** [comment]
@madsrh in any case providing some specs of the gradients or colors you've used could help I guess :)

**Comment by clobrano** [comment]
I just want to say that this might take a bit, since I do not know how to redo background and border images, so I'm going full css :smile:

**Comment by 3v1n0** [comment]
There are some .svg's in the assets dir, but not sure if there are them all.

**Comment by clobrano** [comment]
I almost forgot to commit this :smile: 
So, this is the change of pathbar according to @madsrh's mockup

![image](https://user-images.githubusercontent.com/2883614/38273893-68677750-378d-11e8-8450-d663e47e0de1.png)

![image](https://user-images.githubusercontent.com/2883614/38273927-81b90ade-378d-11e8-9be1-bcf0f5c9909c.png)

I wonder if you would like to consider a version with less shadow, similar to this

![image](https://user-images.githubusercontent.com/2883614/38274074-ee721814-378d-11e8-95c3-053e04061391.png)

**Comment by madsrh** [comment]
As always, this look really good @clobrano but would it be possible to make the border for disabled buttons blend with the background like the mockup?

**Comment by 3v1n0** [comment]
Great @clobrano!

Maybe just a little less shadow, something in between the two would be great :)

**Comment by clobrano** [comment]
@madsrh probably it's because I took the picture with communitheme session

This is another one I took yesterday with Ubuntu default session, with a little less shadow

![image](https://user-images.githubusercontent.com/2883614/38275455-340912ca-3792-11e8-8560-ee5d68ff4afc.png)

**Comment by madsrh** [comment]
@clobrano If there should be a color difference in the button borders, I don't see it :worried: They look like #363632 here. Just so we're not misunderstanding each other, this is what I'm referring to:

![borders](https://user-images.githubusercontent.com/3986894/38276388-2098f5ae-3795-11e8-8363-57c1aeaad927.gif)

**Comment by clobrano** [comment]
My bad, I misunderstood. I'll try with the border

**Comment by clobrano** [comment]
Alright, here a little update. I reduced the shadow (this should be the minimum), and ported the changes on Radiance. 

I spent some time adjusting the border images for the disabled state (there is no button-toolbar image for disabled state), but I must admit I am not happy with the result. Lightening the dark part of the border, makes the bright part shine more, which is undesired of course.

Ambiace
![image](https://user-images.githubusercontent.com/2883614/38457526-bd8e141c-3a91-11e8-932d-dc03a77eebc9.png)

![image](https://user-images.githubusercontent.com/2883614/38457544-f58b98b2-3a91-11e8-82e9-86a3e4a4cb07.png)

Radiance
![image](https://user-images.githubusercontent.com/2883614/38457561-32ed8e7c-3a92-11e8-9c1d-63264428cfaf.png)
![image](https://user-images.githubusercontent.com/2883614/38457565-5039592a-3a92-11e8-936d-e6c9d634f9c3.png)

**Comment by clobrano** [comment]
Thanks to @madsrh, who updated the border images, the change should be ready now

![image](https://user-images.githubusercontent.com/2883614/38464343-9fa88970-3b0c-11e8-81e2-fc3ca38f1c3c.png)

![image](https://user-images.githubusercontent.com/2883614/38464346-a99a83ca-3b0c-11e8-9a40-2d5d96b3adc3.png)
