### ISSUE TITLE
Subiquity (+ conjure-up?): Define visual language for text interface elements

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/desktop-design#3]
In user testing of Subiquity, several of the problems that people experienced had the same root cause: lack of an obvious visual language for interface elements.

This includes things like:
- `(*) radio buttons`
- `[radio menus ↕]`
- `( Push Buttons )`
- `┌─ Dialogs ─┐`
- for those that are controls, what they look like when focused, and when disabled.

We should investigate whether any equivalent work has been done for [conjure-up](https://github.com/conjure-up/conjure-up). If not, it may benefit from this design language too.

**Comment by kwm14** [comment]
Work completed [here](https://github.com/ubuntudesign/vanilla-design/issues/112). Closing issue.
