### ISSUE TITLE
Corner radius on checkboxes looks too similar to radio buttons

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#30]

**Comment by 8none1** [comment]
![radio_checkbox_30](https://user-images.githubusercontent.com/6552931/33713410-fc053652-db42-11e7-941c-1262b4377c2c.png)

**Comment by spencerbygraves** [comment]
@Luxamman @madsrh designs have been added to code in the Check boxes and radio buttons folder.

**Check boxes**
![checkboxes](https://user-images.githubusercontent.com/9105999/35042499-e2521d98-fb80-11e7-880a-96a814cead36.png)

**Radio buttons**
![radio buttons](https://user-images.githubusercontent.com/9105999/35042514-eda45a44-fb80-11e7-9684-1d002b834bb2.png)

**Comment by matthewpaulthomas** [comment]
(Reopening because the bug hasn’t been fixed yet.)

**Comment by matthewpaulthomas** [comment]
This won’t be fixed, since Ubuntu no longer ships Ambiance and Radiance.
