### ISSUE TITLE
Update buttons styles in application header bar

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#32]
Rounded corners & strokes.

**Comment by kwm14** [comment]
Find toolkit Sketch file and identify button styles etc.

**Comment by kwm14** [comment]
## Buttons
I've created a design spec for buttons which details colour, corner radius and strokes of all our different styles of buttons. I have added the spec in Code under Buttons [here](https://github.com/CanonicalLtd/desktop-design/tree/master/Buttons).

![buttons](https://user-images.githubusercontent.com/17748020/35096723-25e41ee8-fc45-11e7-84eb-e9af2656be5f.png)

**Comment by matthewpaulthomas** [comment]
(Reopening because the specified changes haven’t been made yet.)

**Comment by 3v1n0** [comment]
Is still something we want to fix in Ambiance too?

**Comment by 8none1** [comment]
We wont fix this now.  All future work will go towards communitheme and so this issue can be closed.
