### ISSUE TITLE
Gradients in top bar and application header bars clash

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#36]

**Comment by kwm14** [comment]
@8none1 @didrocks can you provide a screenshot so we a visual reference? Thanks

**Comment by matthewpaulthomas** [comment]
Unmaximized, top bar is flat, header bar is convex:
![desktop-design 36 unmaximized](https://user-images.githubusercontent.com/19801137/34943174-76d15032-f9f2-11e7-9113-66a0c6660252.png)

Maximized, top bar is convex, header bar is concave:
![desktop-design 36 maximized](https://user-images.githubusercontent.com/19801137/34943144-57c8a1ae-f9f2-11e7-9438-88e86c8faefc.png)

**Comment by spencerbygraves** [comment]
@Luxamman @madsrh In the latest designs, both the top bar and application bars have a background colour of #111111 with no opacity. When maximised I suggest we keep the colour and opacity the same, and introduce a 1px rule to indicate where the two meet. I've used #666666 from the colour palette.

I will add the designs to code in the Maximised folder.

![image](https://user-images.githubusercontent.com/9105999/35050370-8f6b0c6a-fb9a-11e7-8cf9-d9107013a02e.png)

**Comment by matthewpaulthomas** [comment]
(Reopening because the bug hasn’t been fixed yet.)

**Comment by 3v1n0** [comment]
So the previous state was this: 

![](https://launchpadlibrarian.net/336886030/double_gradient.png)
(see [issue](https://bugs.launchpad.net/ubuntu/+source/ubuntu-themes/+bug/1717023))

So we decided to use an inverted gradient for maximized windows. This works ok, but there are other cases where this doesn't work properly (firefox, thunderbird and chrome mostly).

So, if there is another solution for Ambiance that will work for you, we'll be happy to reconsider this solution.

**Comment by kwm14** [comment]
Design solution resolved [here](https://github.com/CanonicalLtd/desktop-design/issues/47#issuecomment-359801831).

**Comment by matthewpaulthomas** [comment]
This won’t be fixed, since Ubuntu no longer ships Ambiance and Radiance.
