### ISSUE TITLE
Nautilus icon view for focused, selected and mouse-over files is too orange 

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#37]

**Comment by matthewpaulthomas** [comment]
Unselected, focused, and selected:
![desktop-design-37-selected](https://user-images.githubusercontent.com/19801137/35002004-1febe7c0-fae0-11e7-826f-104bccffc61c.png)

**Comment by kwm14** [comment]
## Updated Nautilus icon view
![nautilus-icon-view](https://user-images.githubusercontent.com/17748020/35047664-8a547b6a-fb92-11e7-8190-4108d670a70c.png)

**Comment by kwm14** [comment]
Design spec has been added to Code in the Nautilus icon view folder [here](https://github.com/CanonicalLtd/desktop-design/tree/master/Nautilus%20icon%20view) for reference.

**Comment by matthewpaulthomas** [comment]
(Reopening because the specified changes haven’t been made yet.)

**Comment by 8none1** [comment]
We wont fix this now.  All future work will go towards communitheme and so this issue can be closed.
