### ISSUE TITLE
Update login screen user icon

### ISSUE THREAD

**Issue by kwm14** [CanonicalLtd/desktop-design#38]
- Use Juju GUI icon
- Platform default profile icon

**Comment by 8none1** [comment]
Could someone attach the SVG for the Juju user icon here?

**Comment by meetdilip** [comment]
@8none1 Do you like this ?

![user_avatar_64](https://user-images.githubusercontent.com/6965443/33801806-d09d1e7a-dd8c-11e7-9854-43024e985f8f.png)

**Comment by 8none1** [comment]
@meetdilip thanks, but we already have one from our other projects.  @kwm14 could you ask someone to dig out the juju one and attach it here.

**Comment by kwm14** [comment]
Hi @8none1, looking into Juju's icon set we realised they were using an older version of the icon needed. So I've found an updated version which was used in the Apps and Platform team created by our icon designer.

Please updated user icon attached: [user-icon.svg.zip](https://github.com/CanonicalLtd/desktop-design/files/1558729/user-icon.svg.zip)

**Comment by kwm14** [comment]
Add design to Code section and close.

**Comment by kwm14** [comment]
Icon added to Code section [here](https://github.com/CanonicalLtd/desktop-design/tree/master/User%20icon). Closing issue.

**Comment by matthewpaulthomas** [comment]
(Reopening because the bug hasn’t been fixed yet.)

**Comment by 8none1** [comment]
We wont fix this now.  All future work will go towards communitheme and so this issue can be closed.
