### ISSUE TITLE
Orange selected states look pink

### ISSUE THREAD

**Issue by kwm14** [CanonicalLtd/desktop-design#39]
- Due to reduced transparency on Orange on some screen it looks pink

**Comment by matthewpaulthomas** [comment]
![slider](https://user-images.githubusercontent.com/19801137/33546112-0fda2088-d8d8-11e7-9c19-433266b40007.png)

![listbox](https://user-images.githubusercontent.com/19801137/33546116-13190548-d8d8-11e7-91f6-d36e6a47e862.png)

**Comment by 8none1** [comment]
We wont fix this now.  All future work will go towards communitheme and so this issue can be closed.
