### ISSUE TITLE
Subiquity (+ conjure-up?): Define color scheme

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/desktop-design#4]
Subiquity can use a palette of 8 colors in its text-based interface. The choice of colors would benefit from visual design expertise.

The current palette has something like:
- brand color (currently Ubuntu orange)
- background color (currently black)
- normal text (white)
- secondary text (grey)
- safe continue actions (green)
- dangerous continue actions (red)
- backward actions (blue)

As with #3, we should investigate whether conjure-up has done any equivalent work, and if not, the palette could be used for both.

**Comment by kwm14** [comment]
Work completed [here](https://github.com/ubuntudesign/vanilla-design/issues/113). Closing issue.
