### ISSUE TITLE
Square off Windows and Modals

### ISSUE THREAD

**Issue by 8none1** [CanonicalLtd/desktop-design#41]
They are currently round at the top and square at the bottom

**Comment by 8none1** [comment]
See this post for a suggested fix:

https://community.ubuntu.com/t/ambiance-gnome-theme-bugbears-and-what-can-be-done-about-them/1637/9

If that can be made a MP via a bug on launchpad we can mark this as fixed.

**Comment by matthewpaulthomas** [comment]
This won’t be fixed, since Ubuntu no longer ships Ambiance and Radiance.
