### ISSUE TITLE
Update and provide Action icons

### ISSUE THREAD

**Issue by kwm14** [CanonicalLtd/desktop-design#45]
- Review existing Platform action icons
- Export SVG format

**Comment by kwm14** [comment]
@8none1 @didrocks do these icons need to be provided in the square format?

**Comment by kwm14** [comment]
Speaking with @didrocks 
- Shell only supports the traditional square formats
- Just ship scalable icons as they're reused on different sizes (dialogs, panels etc)

**Comment by spencerbygraves** [comment]
The action icons have been added to code in the Icons folder.
