### ISSUE TITLE
Focussed and non focussed windows

### ISSUE THREAD

**Issue by kwm14** [CanonicalLtd/desktop-design#49]
- Review work done by Platform team
- Review focus state in Vanilla and MAAS
- Design and update accordingly

**Comment by 8none1** [comment]
Background info:  The difference between a focused and unfocused window is not especially
![focussed_and_non_focused_49](https://user-images.githubusercontent.com/6552931/33712977-3bed3cd0-db41-11e7-9d3e-2a05654f36f4.png)
 clear

**Comment by meetdilip** [comment]
Maybe, adding faded grey will do some good. Unfocused windows need not have a darker header similar to the focused window.

**Comment by kwm14** [comment]
## Focussed and non focussed windows

Changing colour and reducing the transparency of path bar items allows users to distinguish between focussed and non-focussed windows.
- Focussed - bottom center window
- Non-focussed - top left window

![focussed-and-non-focussed](https://user-images.githubusercontent.com/17748020/35150496-81d8cfdc-fd12-11e7-8756-f021a9e4876b.png)

**Comment by kwm14** [comment]
Design spec can be found in Code under Focussed and non focussed windows [here](https://github.com/CanonicalLtd/desktop-design/tree/master/Focussed%20and%20unfocussed%20windows).

**Comment by matthewpaulthomas** [comment]
(Reopening because the specified changes haven’t been made yet.)

**Comment by 8none1** [comment]
We wont fix this now.  All future work will go towards communitheme and so this issue can be closed.
