### ISSUE TITLE
Subiquity: Design for bonding and Vlans

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/desktop-design#5]
[Design brief](https://docs.google.com/document/d/1Wz_1SmriM2RJyx0_S0DUVopLAhE-zFomJvyBNfa2Bwc/edit): “In subiquity, networking configuration step allows one to setup ip settings of a networking interface. Currently only physical interfaces are supported such as ethernet and WiFi network cards…”

The rough scope of this work would be specifying:
- a “dialog” for adding a bond
- a “dialog” for adding a Vlan
- buttons on the “Network interfaces” page for accessing each of these dialogs
- some kind of UI for removing an existing bond/Vlan.

**Comment by carlaberkers** [comment]
according to subiquity team, this doesn't require design input at the moment.
Closing
