### ISSUE TITLE
Interface descriptions

### ISSUE THREAD

**Issue by carlaberkers** [CanonicalLtd/desktop-design#6]
@matthewpaulthomas commented on [Wed Aug 16 2017](https://github.com/CanonicalLtd/snappy-design-squad/issues/100)

For the install-time settings UI, the post-install settings UI, and the runtime prompt, each interface needs:
- a human-readable description
- a definition of whether its UI should be a checkbox (most of them) or something else (usually a radio menu).

Implementing these descriptions would be a blocker for implementing:
- #99 end-user install-time settings
- #97 end-user post-install settings
- #98 end-user runtime prompt.

---

@matthewpaulthomas commented on [Thu Aug 17 2017](https://github.com/CanonicalLtd/snappy-design-squad/issues/100#issuecomment-323080036)

According to [the developers in the Snapcraft forum](https://forum.snapcraft.io/t/undocumented-interfaces/1697), the current authoritative list of interfaces is [the list on the snapd GitHub wiki](https://github.com/snapcore/snapd/wiki/Interfaces).

---

@matthewpaulthomas commented on [Mon Aug 21 2017](https://github.com/CanonicalLtd/snappy-design-squad/issues/100#issuecomment-323680049)

[Spreadsheet of current interfaces and proposed descriptions and categories](https://docs.google.com/spreadsheets/d/1cFcHOfKxivaisi5PHiwescVy9veViZQYQeRangrwtOA/edit)

In English, the same descriptions could work in a list of interfaces at install time (“{snap name} will be able to:”) and individually in a runtime prompt (“{snap name} wants to ______”). I’m not certain the same would work in other languages.

---

@matthewpaulthomas commented on [Tue Sep 05 2017](https://github.com/CanonicalLtd/snappy-design-squad/issues/100#issuecomment-327194227)

38/95 interfaces remaining to describe.

**Comment by matthewpaulthomas** [comment]
`<willcooke> The long tail of millions of settings that can be tweak is probably a phase 2 thing as well`
`<willcooke> That spreadsheet you did which highlights the most user understandable ones it a great list to focus on`

**Comment by shivjoshi1996** [comment]
@carlaberkers I think @matthewpaulthomas wanted you to review this work, hence why I added you on to the card.

**Comment by matthewpaulthomas** [comment]
@carlaberkers After I designed [the interface runtime prompts](https://github.com/CanonicalLtd/snappy-design-squad/issues/98), I learned that they would not be implemented for Ubuntu 18.04.

This means that no snap store can rely on the existence of the prompts, unless that store is exclusive to systems _newer_ than Ubuntu 18.04, systems where the prompts are implemented.

The Snap Store is currently the only snap store, and the Snap Store targets all current Ubuntu releases. As long as both those things remain true, the prompts will not appear until Ubuntu 18.04 reaches EOL in 2023.

For that reason, the “{snap name} wants to…” part of the interface descriptions work does not seem useful for Ubuntu 18.04 at least.

After I designed [the interface post-install settings in System Settings](https://github.com/canonicalltd/snappy-design-squad/issues/97), I learned that they too would not be implemented for Ubuntu 18.04. (Not even when I offered to help divide the work into phases.) For that reason, the “Category” and “Label in System Settings” part of the interface descriptions work does not seem useful for Ubuntu 18.04 either.

Therefore, I propose postponing the 127 remaining strings until one or the other feature is implemented. It might turn out that many of the strings I’ve already written will need changing based on the initial implementation.

**Comment by carlaberkers** [comment]
@matthewpaulthomas even if it would be implemented for 18.04, I don't think we should be responsible for these strings. When it comes back up: this is a good example of requests where we can ask the engineering team for a proposal and then we can review.

Calling this descoped and closed for now
