### ISSUE TITLE
First-login window changes

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/desktop-design#61]
Changes are necessary to address comments on [the first-login window design](https://docs.google.com/a/canonical.com/document/d/1IDQwpqTsB7Cmw413ApXioHeO2E9nv8bHugjxCOg9A-Q/edit).

These are urgent because the intention is to ship it with Ubuntu 18.04.

**Comment by matthewpaulthomas** [comment]
Issues resolved:
- Explained why I didn’t try to describe the different data collection frequencies
- Reordered the steps so that Livepatch is before collecting data about whether you use Livepatch
- Livepatch radio buttons and Web frame replaced by a pushbutton…

**Comment by matthewpaulthomas** [comment]
Reviewed with @carlaberkers. Reported #66 for the visual design.

**Comment by madsrh** [comment]
The backwards/forward buttons <> colors looks very similar because they are so far apart. Why not just remove the button completely when it's deactivated?

![image](https://user-images.githubusercontent.com/3986894/38961355-8b8d561e-4368-11e8-932b-6b4e29e844e1.png)
