### ISSUE TITLE
Active tab not attached to notebook

### ISSUE THREAD

**Issue by CDrummond** [CanonicalLtd/desktop-design#63]
In the current implementation of Ambiance (in 17.10 and the PPA for 18.04) tabs are not attached to notebooks.

I'm not 100% familiar with the Gtk terminology (being a Qt person), but the 'frame' of the notebook is completely solid - whereas there should be no line under the active tab.

Current tabs from nautilus:

![screenshot from 2018-03-22 19-00-25](https://user-images.githubusercontent.com/1141694/37792586-11403c42-2e04-11e8-8b5f-52611d88ad85.png)

The following is a crude mockup to demonstrate how this could be improved; the tab is joined to the notebook, and bold text is used for its title:

![n-ed](https://user-images.githubusercontent.com/1141694/37792627-28c20dc8-2e04-11e8-99a4-f464ac3218d7.png)

**Comment by 8none1** [comment]
We wont fix this now.  All future work will go towards communitheme and so this issue can be closed.
