### ISSUE TITLE
Hard to distinguish active item in headerbar

### ISSUE THREAD

**Issue by CDrummond** [CanonicalLtd/desktop-design#64]
I'm not sure of the widgets name, but in the following screenshot for gtk3-widget-factory, its hard to determine which of `Page 1 | Page 2 | Page 3` is active:

![screenshot from 2018-03-22 19-13-50](https://user-images.githubusercontent.com/1141694/37792956-306e729a-2e05-11e8-89c5-611ce4ff5e31.png)

Perhaps the active item should use a bold font?

**Comment by madsrh** [comment]
I believe this is the stackswitcher. What about white text for selected and an inner bevel 3D-ish effect for the button?

![ambiance](https://user-images.githubusercontent.com/3986894/37875109-22ba1f36-303b-11e8-8d7b-79795288a548.jpg)

**Comment by 8none1** [comment]
We wont fix this now.  All future work will go towards communitheme and so this issue can be closed.
