### ISSUE TITLE
Use Kvantum and QGnomePlatform for Qt applications

### ISSUE THREAD

**Issue by CDrummond** [CanonicalLtd/desktop-design#65]
(I'm not 100% sure if this is the correct place for this, or not - so I apologise in advance if it is not...)

Currently Qt apps are set to use the Gtk2 theme via the QGtkStyle plugin. This Qt style uses Gtk2 to paint into pixmaps, which are then drawn where the Qt widgets would be. Whilst this is better than no integration, it has a few issues. e.g. if a Gtk2 style does not use scrollbar arrows, Qt still reserves space for these - but nothing is drawn. Its also Gtk2 based.

I'd like to suggest that Ubuntu uses [QGnomePlatform,](https://github.com/MartinBriza/QGnomePlatform) [Adwaita-Qt,](https://github.com/MartinBriza/adwaita-qt) and [Kvantum.](https://github.com/tsujan/Kvantum) to help integrate Qt apps with GNOME shell.

QGnomePlatform is a Qt ‘platform’ plugin - it allows Qt apps to use some Gtk dialogs (file picker, colour picker, etc), sets the Qt font to match Gtks, and tries to set a matching Qt theme for the Gtk theme.

Adwaita-Qt is a Qt Adwaita inspired theme, and its a pretty close approximation (only the ‘overlay’ scrollbars are not as nice).

Kvantum is a SVG based theming ‘engine.’ Kvantum already ships with a KvAmbiance theme which is a pretty good match for Ambiance. (Kvantum is (AFAIK) the only Qt theme which has Gtk-like overlay scrollbars). Kvantum’s author has also volunteered to make a Kvantum equivalent of the community theme, when this is more settled down.

QGnomePlatform will ascertain the user’s Gtk theme. If it finds a matching Kvantum theme, it will set Qt to use Kvantum and configure Kvantum to use the theme. If the user is using Adwaita, then Adwaita-Qt will be chosen. This all happens automatically - it just needs Qt configured to use QGnomePlatform as its QPA platform - this can be achieved by setting `QT_QPA_PLATFORMTHEME=gnome`

Both QGnomePlatform and Adwaita-Qt have been developed by a RedHat employee, and are already used in Fedora.

**Comment by pojntfx** [comment]
I wrote about this in the community hub some time back as well. Kvantum even has the Ambiance theme right now!

**Comment by CDrummond** [comment]
This can probably be closed. KVantum's author has refused a request to change from GPL to LGPL, and from discussions on the community hub this would appear to be a blocking issue for Ubuntu including this by default.
