### ISSUE TITLE
Visual design for first-login window

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/desktop-design#66]
[The first-login window](https://docs.google.com/a/canonical.com/document/d/1IDQwpqTsB7Cmw413ApXioHeO2E9nv8bHugjxCOg9A-Q/edit) needs visual design. In particular:
- The “What’s new in Ubuntu” screen needs a screenshot of a pristine Ubuntu 18.04 setup with one non-maximized window open.
- The “Get more apps” screen needs mocking up to illustrate how current and available apps should be laid out.
- Those two screens in particular influence how big the window should be overall.

**Comment by spencerbygraves** [comment]
**First-login window**
![image](https://user-images.githubusercontent.com/9105999/38095647-df77bdec-3368-11e8-9f20-a1a3fe0d3ccf.png)

**Livepatch**
![image](https://user-images.githubusercontent.com/9105999/38095689-f4cbee98-3368-11e8-99ef-7744fa5583d5.png)

**Help improve Ubuntu**
![image](https://user-images.githubusercontent.com/9105999/38095722-06b1e752-3369-11e8-9ffe-78dc9462aab5.png)

**Get more apps**
![image](https://user-images.githubusercontent.com/9105999/38095859-5c085f56-3369-11e8-8abb-a2c0e88cbbf1.png)

**Comment by 8none1** [comment]
In First Login Window the "Application Switcher" is actually "Application Menu".  But, it's not all menus, only some (!) so I don't know how to explain it properly.  Application Menu is probably OK for now.

**Comment by carlaberkers** [comment]
@8none1 I'm not sure what @matthewpaulthomas original intention was but I guess we could highlight activities instead if that is ok with him?

How would you build that screen, do you need an asset with the images and text next to it or do you need just the image? We'll need to ask @kwm14 to help with the assets as @spencerbygraves is on holiday this week.

**Comment by 8none1** [comment]
Re: building the screen - it would be a lot easier for us to take the image, complete with labels in the correct location.  Trying to place text at exactly the right location will be very hard because people could resize the window/have different screen sizes, dpis etc.

**Comment by carlaberkers** [comment]
Alright, will ask if one of the other visual designers can prepare it for you tomorrow.

**Comment by carlaberkers** [comment]
@lyubomir-popov will look into @spencerbygraves files and update the file. Lyubo you can find will on IRC as willcooke if you have any questions

**Comment by lyubomir-popov** [comment]
Trying to locate files @spencerbygraves worked on. This should be discoverable in dropbox's history, but I only see the 20 or so most recent changes and this file is not among them. @pmahnke could you help?

**Comment by lyubomir-popov** [comment]
Agreed with Will to follow up on Monday as I can't locate the files.

**Comment by lyubomir-popov** [comment]
@8none1 Does this look ok? 
![first-login window](https://user-images.githubusercontent.com/2741678/38614047-b86d1862-3d83-11e8-9e1c-79d011f9f52b.png)

**Comment by 8none1** [comment]
Looks good, thanks!

**Comment by carlaberkers** [comment]
@lyubomir-popov can you please provide the asset on a transparent backgound?

@robert-ancell per explicit request from @jamiedbennett we show only featured snaps, not the installed ones.

**Comment by lyubomir-popov** [comment]
@robert-ancell Are the images below ok? Tightly cropped and exported at 1x, 2x, 3x. Let me know if you prefer more white space around the edges.

![new features 3x](https://user-images.githubusercontent.com/2741678/38669961-7a281298-3e3f-11e8-8b10-c9211be775eb.png)
![new features 1x](https://user-images.githubusercontent.com/2741678/38669962-7a402f5e-3e3f-11e8-994d-171c70f263fb.png)
![new features 2x](https://user-images.githubusercontent.com/2741678/38669963-7a584f08-3e3f-11e8-90ff-906a710016f6.png)

**Comment by robert-ancell** [comment]
@lyubomir-popov they look perfect! I can add margins around the image as necessary.

**Comment by lyubomir-popov** [comment]
@robert-ancell Great, can we close this?

**Comment by 8none1** [comment]
Is it possible to get an SVG of this image so that we can make the strings translatable?

**Comment by jbicha** [comment]
I filed https://github.com/CanonicalLtd/desktop-design/issues/101

**Comment by robert-ancell** [comment]
Thanks @lyubomir-popov for the images. I think it's going to be quite hard to get either technique to work well in GTK+ but I'll try my best...

**Comment by jbicha** [comment]
And https://github.com/CanonicalLtd/desktop-design/issues/105 is another follow-up.

**Comment by robert-ancell** [comment]
I just implemented translatable support for this by using an image without labels and adding GTK+ elements to draw the translatable labels. In doing this I noticed that the "Close button" label is likely to overlap the background if it gets longer. So I think we need to move it outside the background (as shown in the WIP below). @lyubomir-popov - does this seem like a reasonable solution and if so, could you generate an image with something nicer than my MsPaint quality line?

![screenshot from 2018-05-04 16-55-10](https://user-images.githubusercontent.com/126560/39613576-4cf5c6b0-4fbc-11e8-8efb-b617581dea4f.png)

Using background with this form/resolution:
![ubuntu-changes](https://user-images.githubusercontent.com/126560/39613656-de808980-4fbc-11e8-9dfc-db93ec7329a6.png)

**Comment by lyubomir-popov** [comment]
hi @robert-ancell, just to confirm - which image format did you use svg or png? attaching a png but if you prefer I'll export as svg too.

![first-login window embedded](https://user-images.githubusercontent.com/2741678/39621544-0be7fc7c-4f87-11e8-94ff-f8421deb8254.png)

**Comment by robert-ancell** [comment]
I did use .png, thanks

**Comment by robert-ancell** [comment]
Note the provided image is higher resolution and not tightly cropped - I'm happy to crop and scale before using it, or should it be regenerated?

**Comment by robert-ancell** [comment]
I scaled and cropped to this:

![ubuntu-changes](https://user-images.githubusercontent.com/126560/39736566-bdc8eeec-52d4-11e8-8ac1-c01d00cd5474.png)

Which looks like this in the window:
![screenshot from 2018-05-08 15-30-59](https://user-images.githubusercontent.com/126560/39736580-d278dff0-52d4-11e8-8118-b1d7ac6c6029.png)

Shout out if this looks wrong.

**Comment by lyubomir-popov** [comment]
@robert-ancell The higher resolution was to account for retina displays (your screenshot looks  a little blurry on my screen). Can you give me the exact width and height you need? I'll can give you two files, one at 1x and one at 2x resolution for higher res screens.

**Comment by robert-ancell** [comment]
@lyubomir-popov the screenshot above is the window space we have available for the image - so it can be any size as long as it leaves enough space for the labels. The scale of the original images seems appropriate to me. Other than that, just make it tightly cropped and I can add appropriate spacing for the labels.

I'm currently finding out how to do high-dpi support in GTK+.

**Comment by lyubomir-popov** [comment]
@robert-ancell Attaching tightly cropped versions. Could you leave more space between the second line of copy and the image? Not sure what the standard vertical spacing amounts used in ubuntu are, but roughly 2 empty lines of copy worth of white space (or line-heights if it is html-like) would be better I think.

![first-login window embedded 2x](https://user-images.githubusercontent.com/2741678/39932802-0d4fe022-5539-11e8-96ba-a50316240f29.png)
![first-login window embedded 1x](https://user-images.githubusercontent.com/2741678/39932806-106cfba0-5539-11e8-8aaf-fac34531fd01.png)
